### ISSUE TITLE
Support reading/submitting ISRCs

### ISSUE THREAD

**Issue by kepstin** [kepstin/image-id#1]
Some image formats contain enough information to get isrcs out. See if libmirage interfaces can be used for this, and support submitting them.

**Comment by kepstin** [comment]
Recent versions of libmirage offer the function [mirage_track_get_isrc()](http://cdemu.sourceforge.net/reference/libmirage-MIRAGE-Track-object.html#mirage-track-get-isrc) which should do this.

**Comment by JonnyJD** [comment]
Looks like the documentation links for libmirage aren't stable either:
http://cdemu.sourceforge.net/reference/MirageTrack.html#mirage-track-get-isrc -> mirage_track_get_isrc()
